# config.yaml

factors:
  mutation_rate: 1.0e-8 ## mutation rate per bp per gen
  recombination_rate: 3.0e-9 # Arbitary but intentionally kept 1 order lower than mutation rate
  population_size : 50000 # diploid so become 100000
  keep_individual : 50 # diploid so in turn become 100
  sequence_length : 100000 #100 kilobases
  when_bottleneck : 9999 ## add the number 1000 to it
  lowest_i : 0.001 # lowest bottleneck intensity
  highest_i : 1 # highest bottleneck intensity
  num_of_data : 5000 # numbers of different data points